install script cleanup dummy bak file
Azure/acr-docker-credential-helper pull request #15
Opened 2017-06-16 22:20 UTC by shhsu

Right now, if you don't have a config file already. The installer will create a temporary one because config-edit, being just an editor, assumes a config file is already there.

That dummy file should not be backed up.

2017-06-16 22:20 UTC, msftclas commented
@shhsu,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-19 18:42 UTC, shhsu commented
@DavidObando

2017-06-19 23:20 UTC, DavidObando commented on install/install.ps1
> +if ($dummyConfigCreated) {
Shouldn't this be negated? I see it's negated in the bash script.

2017-06-19 23:21 UTC, DavidObando commented on install/install.ps1
> +    Remove-Item -Force "${configFile}.bak"
Can you check if the file exists before trying to remove it? Just so it's cleaner. Same for the bash script.

2017-06-19 23:22 UTC, DavidObando requested changes
I just had a couple of observations. Let me know what you think.

2017-06-19 23:37 UTC, DavidObando approved these changes

2017-06-19 23:37 UTC, merged