Package artifacts for all OS and README update
Azure/acr-docker-credential-helper pull request #6
Opened 2017-06-14 22:45 UTC by shhsu

2017-06-14 22:45 UTC, msftclas commented
@shhsu,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-14 22:45 UTC, shhsu commented
@sajaya @davidobando

2017-06-15 00:36 UTC, DavidObando requested changes
A few changes are needed.

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +This is a wrapper for Docker Credential helpers created by Azure Container Registry (ACR) team. This credential helper make use of Azure Active Directory (AAD) to obtain and maintain user's credentia
Please change to something like:

The ACR Docker Credential Helper allows users to sign-in to the Azure Container Registry service using their Azure Active Directory (AAD) credentials. This credential helper is in charge of ensuring that the stored credentials are valid, and when required it also renews the credentials for a repository.

For now, this credential helper works in tandem with the Azure CLI, which is required in order to initiate the credential flow. Once you've successfully logged in to your container registry with the Azure CLI, the credential helper administers the life cycle of your locally stored credential.

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +- Docker installation is required, of course.
Change to:
```
- [Docker](https://www.docker.com/)
```

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +`iex ([System.Text.Encoding]::ASCII.GetString((Invoke-WebRequest -Uri https://aka.ms/acr/installaad/win).Content))`
Consider using `UTF8` instead.

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +After that, you will be able to use docker normally. This credential helper would help maintaining your AAD access tokens.
Change the last part to: This credential helper will help maintaining your credentials valid.

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +For linux, run the [bash installation script](https://aka.ms/acr/installaad/bash) as root:
For Linux and macOS,

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +To login to an ACR service as followed:
Change to:
After installing the ACR Docker Credential Helper, login to an Azure Container Registry using the Azure CLI:

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +    If you have not called `az acr login -n <registry>` to log in to your registry for extended period of time, please re-login with that command. If you find yourself having to re-login every hour o
If you have not called `az acr login -n <registry>` to log in to your registry for extended period of time and you get a 401 error, please login again. If you find yourself having to re-login every hour or so, make sure your computer clock is set to the correct time.

2017-06-15 00:36 UTC, DavidObando commented on README.md
> +- Why am I getting 401 error (authentication required)?
Change for:
```
### Getting 401 (authentication required)
```

2017-06-15 00:36 UTC, DavidObando commented on install/install.ps1
>      Write-Error "Please install docker first"
Change to:
Write-Error "Cannot find docker in path. Ensure it's installed and that its path is accessible."

2017-06-15 00:36 UTC, DavidObando commented on install/install.sh
>  if [[ "$unamestr" == "Linux" ]]; then
This is not needed. Given the updates to the build scripts, we'll download from `baseurl` for the specific OS (Linux or Darwin). Let's sync about this in the morning.

2017-06-15 17:34 UTC, DavidObando commented on README.md
> +For Linux and MacOS, run the [bash installation script](https://aka.ms/acr/installaad/bash) as root:
macOS has a lowercase m.

2017-06-15 17:35 UTC, DavidObando commented on build/build-config-edit.sh
> +    outputFile="${bindir}/${go_os}/config-edit-${go_os}${exe_extension}"
We already have `$go_os` in the filename, why also in the path?

2017-06-15 17:39 UTC, DavidObando commented on build/package.sh
> +for osname in $(ls $binroot) ; do
I see, so you used `$go_os` in the path above so you could do this. I recommend you simply loop around "linux", "darwin" and "windows".

2017-06-15 17:40 UTC, DavidObando commented on build/package.sh
> +        pkgName="docker-credential-acr-${osname}-amd64"
Set "amd64" in a variable and append the variable here. We may build this helper for other architectures in the future and we want to have this ready to go.

2017-06-15 17:55 UTC, DavidObando commented on src/docker-credential-acr/acr_login.go
> +			logrus.Infof("[Azure Login Helper] server %s does not responded with a valid challenge, reverting to default login...\nerror: %s\n", serverAddress, err)
Typo, change to:
```go
logrus.Infof("[Azure Login Helper] server %s didn't respond with a valid challenge, reverting to default login...\nerror: %s\n", serverAddress, err) 
```

2017-06-15 18:29 UTC, shhsu commented on build/package.sh
> +for osname in $(ls $binroot) ; do
Same as above

2017-06-15 18:29 UTC, shhsu commented on build/build-config-edit.sh
> +    outputFile="${bindir}/${go_os}/config-edit-${go_os}${exe_extension}"
It makes the bin folder more neat. Right now all binaries are in the same directory.

2017-06-15 18:37 UTC, DavidObando approved these changes

2017-06-15 18:42 UTC, shhsu commented on src/docker-credential-acr/acr_login.go
> +			logrus.Infof("[Azure Login Helper] server %s does not responded with a valid challenge, reverting to default login...\nerror: %s\n", serverAddress, err)
FYI, I have now fixed the typo (see file changed tab) but somehow the PR comment section didn't show it's fixed.

2017-06-15 18:55 UTC, merged